name: "🐞 Bug Report"
description: Report an issue with node-mapped-buffers
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell in the description. Thanks!
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Contributing Guidelines](https://github.com/FynniX/node-mapped-buffer/blob/main/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](TODO).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/FynniX/node-mapped-buffer/issues) that reports the same bug to avoid creating a duplicate.
          required: true