name: Test

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup environment
        run: pnpm install

      - name: Run check for linting errors
        run: pnpm run lint

      - name: Run check for formatting errors
        run: pnpm run format

      - name: Run unit tests
        run: pnpm run test
