name: Test

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: ANTLR4 Installation
        run: pip install --no-input antlr4-tools

      - name: Setup environment
        run: pnpm install

      - name: Run check for linting errors
        run: pnpm run lint

      - name: Run check for formatting errors
        run: pnpm run format

      - name: Run unit tests
        run: pnpm run test
